name: bitcoin-dance
static_sites:
  - name: web
    github:
      deploy_on_push: true
      branch: main
      repo: masonforest/bitcoin.dance
    dockerfile_path: Dockerfile.static
    output_dir: /app/public